#!/bin/sh
# rootfs read-write, then everything else in fstab
. /usr/lib/s6-rc/rc.lib
case $1 in
up)
    log "remounting rootfs read-write..."
    mount -o remount,rw / || sos
    log "mounting local filesystems..."
    # no_netdev because there is no network at this point in the boot and a
    # network mount in fstab would block
    mount -a -O no_netdev || sos
    ;;
down)
    # unmounting is done via s6-linux-init-unmountall, this is just here to
    # make certain nothing is mid-write when that happens
    sync
    ;;
esac
exit 0
